### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nicolasroger17** [fdintino/nginx-upload-module#105]
Hi,

I am trying to build a Docker image for `nginx` with this module.

I took the official nginx image:
https://github.com/nginxinc/docker-nginx/blob/ddbbbdf9c410d105f82aa1b4dbf05c0021c84fd6/mainline/alpine/Dockerfile
and I've made a few modifications to add the `nginx-upload-module` module.

I've been trying with the following versions of nginx so far:
- 1.15.2
- 1.13.9

I've run into the `md5.h`/`sha.h` issue, which I've addressed thanks to @Austinb comment:
https://github.com/fdintino/nginx-upload-module/issues/79

Though now, I'm getting the following error during the `make` command:
```
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c: In function 'ngx_http_upload_merge_ranges':
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c:1673:18: error: variable 'result' set but not used [-Werror=unused-but-set-variable]
     int          result;
                  ^~~~~~
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c: In function 'ngx_http_read_upload_client_request_body':
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c:2620:15: error: 'ngx_http_request_body_t {aka struct <anonymous>}' has no member named 'to_write'
             rb->to_write = rb->bufs;
               ^~
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c:2679:7: error: 'ngx_http_request_body_t {aka struct <anonymous>}' has no member named 'to_write'
     rb->to_write = rb->bufs;
       ^~
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c: In function 'ngx_http_do_read_upload_client_request_body':
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c:2761:57: error: 'ngx_http_request_body_t {aka struct <anonymous>}' has no member named 'to_write'
                 rc = ngx_http_process_request_body(r, rb->to_write);
                                                         ^~
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c:2777:19: error: 'ngx_http_request_body_t {aka struct <anonymous>}' has no member named 'to_write'
                 rb->to_write = rb->bufs->next ? rb->bufs->next : rb->bufs;
                   ^~
/usr/src/nginx-upload-module-2.2.0/ngx_http_upload_module.c:2869:45: error: 'ngx_http_request_body_t {aka struct <anonymous>}' has no member named 'to_write'
     rc = ngx_http_process_request_body(r, rb->to_write);
                                             ^~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1784: objs/addon/nginx-upload-module-2.2.0/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory '/usr/src/nginx-1.13.9'
make: *** [Makefile:8: build] Error 2
```

The first error, `unused-but-set-variable`, can be fixed by removing the flag from the Makefile.
But `has no member named 'to_write'` looks like a code issue.

Can you tell me which versions of nginx are supported, if the latest are not

**Comment by nicolasroger17** [comment]
I've just noticed that the `2.2.0` release is from `2010`.
I've recompiled using `master` and everything is fine.

I'm not sure I'm the one who will run into this issue, so I think it'd be great to create a `2.2.1` or `2.3.0` release.

**Comment by fdintino** [comment]
Oh, I didn't even realize that there is no 2.3.0 release. I'll create one.

**Comment by fdintino** [comment]
I created a 2.3.0 release with the latest changes from master. Thanks!
