### ISSUE TITLE
unknown directive "upload_pass" (with Nginx-1.14.0)

### ISSUE THREAD

**Issue by hank-cp** [fdintino/nginx-upload-module#110]
Compilation succeeded, but failed with `service nginx configtext`
```
unknown directive "upload_pass" in /etc/nginx/sites-enabled/default:83
```

Same build environment works with Nginx version 1.12 and 1.10.

**Comment by cbj4074** [comment]
@hank-cp Any chance you're using https://github.com/masterzen/nginx-upload-progress-module , in conjunction with this module?

I've noticed that if I use any version of that module > v0.9.0, in conjunction with this module, I have the same problem.

As soon as I go back to v0.9.0, coupled with 2.3.0 of this module, NGINX compiles perfectly well.

**Comment by hank-cp** [comment]
@cbj4074 No, I am not using the *upload progress module*, only coupled with this module.

BTW, where did you find the 2.3.0 version of this module? I only see 2.225 branch in the code base.

**Comment by cbj4074** [comment]
@hank-cp It's a tag, not a branch:

https://github.com/fdintino/nginx-upload-module/tree/2.3.0

If you were building with an older version, that could certainly cause the issue you describe.

**Comment by hank-cp** [comment]
@cbj4074 Thanks, build with 2.3.0 solved my problem. Thanks a lot. This Issue could be closed now.
