### ISSUE TITLE
Problem with compiling 2.2 with nginx 1.19

### ISSUE THREAD

**Issue by bdbais** [fdintino/nginx-upload-module#133]
wget http://nginx.org/download/nginx-1.19.0.tar.gz
wget http://www.grid.net.ru/nginx/download/nginx_upload_module-2.2.0.tar.gz

some changes on source : 
 MD5_ istead MD5   
<openssl/md5.h> instead  <md5.h>   

I lot of 'no-unused-but-set-variable' error messages , totally false (I checked the code). but I removed the warning.

` cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.2.1-9ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)
`

```
CFLAGS=-Wno-unused-but-set-variable ./configure --sbin-path=/usr/local/nginx/nginx --conf-path=/usr/local/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-http_ssl_module --with-zlib=../zlib-1.1.3 --add-module=/root/modules/nginx_upload_module-2.2.0

make 

make -f objs/Makefile
make[1]: Entering directory '/root/modules/nginx-1.19.0'
cc -c -Wno-unused-but-set-variable   -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../zlib-1.1.3 -I objs -I src/http -I src/http/modules \
        -o objs/addon/nginx_upload_module-2.2.0/ngx_http_upload_module.o \
        /root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c: In function ‘ngx_http_read_upload_client_request_body’:
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c:2628:15: error: ‘ngx_http_request_body_t’ {aka ‘struct <anonymous>’} has no member named ‘to_write’
 2628 |             rb->to_write = rb->bufs;
      |               ^~
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c:2687:7: error: ‘ngx_http_request_body_t’ {aka ‘struct <anonymous>’} has no member named ‘to_write’
 2687 |     rb->to_write = rb->bufs;
      |       ^~
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c: In function ‘ngx_http_do_read_upload_client_request_body’:
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c:2769:57: error: ‘ngx_http_request_body_t’ {aka ‘struct <anonymous>’} has no member named ‘to_write’
 2769 |                 rc = ngx_http_process_request_body(r, rb->to_write);
      |                                                         ^~
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c:2785:19: error: ‘ngx_http_request_body_t’ {aka ‘struct <anonymous>’} has no member named ‘to_write’
 2785 |                 rb->to_write = rb->bufs->next ? rb->bufs->next : rb->bufs;
      |                   ^~
/root/modules/nginx_upload_module-2.2.0/ngx_http_upload_module.c:2877:45: error: ‘ngx_http_request_body_t’ {aka ‘struct <anonymous>’} has no member named ‘to_write’
 2877 |     rc = ngx_http_process_request_body(r, rb->to_write);
      |                                             ^~
make[1]: *** [objs/Makefile:1235: objs/addon/nginx_upload_module-2.2.0/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory '/root/modules/nginx-1.19.0'
make: *** [Makefile:8: build] Error 2
```
-----------

any advice how to compile 2.2 with nginx-1.19 ?

----------------
the problem I'm trying to resolve is  nginx + django  multiple file, only first is passed to /media and next ones are on request.FILES but not on filesystem.

**Comment by bdbais** [comment]
https://pastebin.com/fANJnEDR
https://pastebin.com/nG8kPeeT

**Comment by soulteary** [comment]
I've test it with 1.20 / 1.21, if you use docker or ubuntu/debian, you can use pre-built modules directly.

https://github.com/nginx-with-docker/ngx_http_upload_module

**Comment by fdintino** [comment]
nginx 2.2.0 is over a decade old. You want to use 2.3.0 ([tar.gz](https://github.com/fdintino/nginx-upload-module/archive/refs/tags/2.3.0.tar.gz))
