### ISSUE TITLE
Upload to fastcgi backend

### ISSUE THREAD

**Issue by mxlang** [fdintino/nginx-upload-module#135]
Hi,
I found this issue: [Issue #69](https://github.com/fdintino/nginx-upload-module/issues/69), from which I understand that renaming the uploaded file should be handled on the backend. I am however missing some info to achieve that! 
I am using a fastcgi backend script to handle the upload. I can successfully upload the file and use the fastcgi script to process the uploaded file. The only part missing is how I can pass the original filename to the script. 
There is the `upload_set_form_field` directive which sets the `$upload_file_name` variable, but I don't know how to use it.
There must be a way to pass the filename to the fastcgi script using the `fastcgi_param` directive, but I cannot figure out how to do it! If someone could help fill the missing link I would be grateful!
Thanks!

**Comment by mxlang** [comment]
I've changed my config to pass the uploaded file name in the request uri, that way I can extract it in my cgi script.

**Comment by xjy198903** [comment]
How does the backend know the correspondence between the temporary file name and the real file name
