### ISSUE TITLE
behind upload_pass only can use php?

### ISSUE THREAD

**Issue by shaozhihua** [fdintino/nginx-upload-module#138]
I know we should write a url behind "upload_pass"
means the handle of file which uploaded,but I look through on the internet ,all of the handle is php?

**Comment by shaozhihua** [comment]
is this true??I use pistache with C++ can not handle the file???

**Comment by mdineen** [comment]
No, any http server will work. [Django](https://github.com/vsoch/django-nginx-upload), [Node](https://www.codeproject.com/Articles/1101103/Gigabit-File-uploads-Over-HTTP-The-Node-js-with-NG), [ASP.net](https://stackoverflow.com/questions/53775239/asp-net-core-large-file-upload-in-nginx-connection-timeout-issue).

**Comment by MarcoRizk** [comment]
Using Django backend is working fine for me

**Comment by xiongshiyan** [comment]
any web server that can accept files，like php，java，go，node，etc.

**Comment by shaozhihua** [comment]
I understand the url behind upload_pass can handle the file's attribute 。what I mean is when I print the request message body,I get a long string,which include all file attribute the upload server send.
