### ISSUE TITLE
2.2 Compile

### ISSUE THREAD

**Issue by swasheck** [fdintino/nginx-upload-module#19]
When compiling nginx with this module I get the following errors - please advice:
/root/src/nginx-upload-module//ngx_http_upload_module.c: In function ngx_http_upload_merge_loc_conf:/root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: error: ngx_garbage_collector_temp_handler undeclared (first use in this function)
/root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: note: each undeclared identifier is reported only once for each function it appears in /root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: error: passing argument 1 of ngx_conf_merge_path_value from incompatible pointer type [-Werror]
src/core/ngx_file.h:140:7: note: expected struct ngx_conf_t \* but argument is of type struct ngx_path_t \* 
/root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: error: passing argument 2 of ngx_conf_merge_path_value from incompatible pointer type [-Werror]
src/core/ngx_file.h:140:7: note: expected struct ngx_path_t *\* but argument is of type struct ngx_path_t *
/root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: error: passing argument 3 of ngx_conf_merge_path_value from incompatible pointer type [-Werror]
src/core/ngx_file.h:140:7: note: expected struct ngx_path_t \* but argument is of type char *
/root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: error: passing argument 4 of ngx_conf_merge_path_value makes pointer from integer without a cast [-Werror]
src/core/ngx_file.h:140:7: note: expected struct ngx_path_init_t \* but argument is of type int
/root/src/nginx-upload-module//ngx_http_upload_module.c:1104:31: error: too many arguments to function ngx_conf_merge_path_value
src/core/ngx_file.h:140:7: note: declared here
/root/src/nginx-upload-module//ngx_http_upload_module.c: In function ngx_http_upload_pass_form_field:
/root/src/nginx-upload-module//ngx_http_upload_module.c:1490:5: error: passing argument 1 of ngx_regex_compile from incompatible pointer type [-Werror]
src/core/ngx_regex.h:45:11: note: expected struct ngx_regex_compile_t \* but argument is of type struct ngx_str_t *
/root/src/nginx-upload-module//ngx_http_upload_module.c:1490:5: error: too many arguments to function ngx_regex_compile
src/core/ngx_regex.h:45:11: note: declared here
/root/src/nginx-upload-module//ngx_http_upload_module.c:1490:14: error: assignment makes pointer from integer without a cast [-Werror]
/root/src/nginx-upload-module//ngx_http_upload_module.c:1497:5: error: implicit declaration of function ngx_regex_capture_count [-Werror=implicit-function-declaration]
/root/src/nginx-upload-module//ngx_http_upload_module.c:1501:28: error: ngx_regex_capture_count_n undeclared (first use in this function)
/root/src/nginx-upload-module//ngx_http_upload_module.c:1501:54: error: expected) before string constant
cc1: all warnings being treated as errors

make[1]: **\* [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/root/src/nginx-1.0.1'
make: **\* [build] Error 2

**Comment by vanjulchrist** [comment]
Hi guys,

i just suggest you to recompiling the nginx-upload module with this source.

`git clone -b 2.2 git://github.com/vkholodkov/nginx-upload-module.git nginx-upload-module-2.2m`

I have tried this by my side with my latest nginx version 1.10.2.
