### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by MarkMil** [fdintino/nginx-upload-module#36]
Here is the output from a core dump using gdb:

Core was generated by `nginx: worker process                                          '.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004b8eb4 in ngx_http_do_read_upload_client_request_body (r=0x1fe6bc70) at nginx-upload-module/ngx_http_upload_module.c:3031

3031                if (u->limit_rate) {
(gdb) bt
#0  0x00000000004b8eb4 in ngx_http_do_read_upload_client_request_body (r=0x1fe6bc70) at nginx-upload-module/ngx_http_upload_module.c:3031
#1  0x00000000004b8af4 in ngx_http_read_upload_client_request_body_handler (r=0x1fe6bc70) at nginx-upload-module/ngx_http_upload_module.c:2976
#2  0x0000000000450b08 in ngx_http_request_handler (ev=0x1ff06ba0) at src/http/ngx_http_request.c:1867
#3  0x000000000042ad74 in ngx_event_process_posted (cycle=0x1fdc3750, posted=0x89bbc8) at src/event/ngx_event_posted.c:40
#4  0x0000000000428a39 in ngx_process_events_and_timers (cycle=0x1fdc3750) at src/event/ngx_event.c:274
#5  0x0000000000435a69 in ngx_worker_process_cycle (cycle=0x1fdc3750, data=0x0) at src/os/unix/ngx_process_cycle.c:806
#6  0x00000000004325c1 in ngx_spawn_process (cycle=0x1fdc3750, proc=0x4358bd <ngx_worker_process_cycle>, data=0x0, name=0x5dfc7e "worker process", respawn=-3) at src/os/unix/ngx_process.c:198
#7  0x000000000043496f in ngx_start_worker_processes (cycle=0x1fdc3750, n=4, type=-3) at src/os/unix/ngx_process_cycle.c:365
#8  0x0000000000434026 in ngx_master_process_cycle (cycle=0x1fdc3750) at src/os/unix/ngx_process_cycle.c:137
#9  0x0000000000404499 in main (argc=3, argv=0x7fffbce8ac88) at src/core/nginx.c:410

**Comment by mvrhov** [comment]
I'm having very similar segmentation fault with latest version from 2.2 branch. The line number are a bit different but otherwise it looks the same.
Mark did you figure something out?

**Comment by khavishbhundoo** [comment]
@fdintino I think this can be safely closed as well
