### ISSUE TITLE
Content-Type boundary with double quotes failure

### ISSUE THREAD

**Issue by canassa** [fdintino/nginx-upload-module#50]
There is a bug with the Nginx Upload Module when the HTTP boundary header contains a double quote, e.g.:

```
Content-Type: multipart/form-data; boundary="MyBoundary"
```

without the double quotes, the request works fine, e.g.:

```
Content-Type: multipart/form-data; boundary=MyBoundary
```

The upload module includes the double quotes in the actual boundary, thus failing to parse the multipart body content.

**Comment by Viacheslav01** [comment]
Windows Phone HttpClient use a quoted boundary, so the windows phone could not be a client of the module. Fix it please.

**Comment by spragchris** [comment]
.NET HttpClient (not just Windows Phone) uses quoted boundary.
