### ISSUE TITLE
Can't build nginx with --add-module=nginx-upload-module

### ISSUE THREAD

**Issue by Mimikoo** [fdintino/nginx-upload-module#59]
This is the make error:
cc -c -I /home/mimiko/src/nginx-modules/ngx_http_js_module/src/  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I/opt/GeoIP/include -I/opt/gperftools/include -I/opt/ffmpeg/include -I/opt/ImageMagick/include/ImageMagick-6 -Wno-error=unused-but-set-variable -DMAGICKCORE_QUANTUM_DEPTH=32 -DMAGICKCORE_HDRI_ENABLE=0 -DNDK_SET_VAR -I/home/mimiko/src/nginx-modules/nginx-rtmp-module -I/home/mimiko/src/nginx-modules/ngx_http_lower_upper_case -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -I/home/mimiko/src/nginx-modules/ngx_http_php_session -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -Wno-unused-function -Wno-missing-field-initializers -D_POSIX_C_SOURCE=200112L --std=c99 -Isrc  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /home/mimiko/src/nginx-modules/ngx_devel_kit/objs -I objs/addon/ndk -I /opt/libpq/include -I /opt/spidermonkey/include -I /home/mimiko/src/nginx-modules/nginx-video-thumbextractor-module/src -I /home/mimiko/src/nginx-modules/nginx-video-thumbextractor-module/include -I /opt/sregex/include -I /opt/luajit/include/luajit-2.0 -I /opt/luajit/include/luajit-2.0 -I /home/mimiko/src/nginx-modules/lua-nginx-module/src/api -I /home/mimiko/src/nginx-modules/nginx-push-stream-module/src -I /home/mimiko/src/nginx-modules/nginx-push-stream-module/include -I /home/mimiko/src/nginx-modules/nginx_http_push_module/src -I /home/mimiko/src/nginx-modules/nginx-selective-cache-purge-module/src -I /home/mimiko/src/nginx-modules/nginx-selective-cache-purge-module/include -I ../pcre -I ../openssl/.openssl/include -I ../zlib -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/modules/perl -I /home/mimiko/src/nginx-modules/ngx_devel_kit/src -I /home/mimiko/src/nginx-modules/nginx-upload-module -I /home/mimiko/src/nginx-modules/healthcheck_nginx_upstreams -I /home/mimiko/src/nginx-modules/nginx-http-sysguard -I src/mail \
                -o objs/addon/nginx-upload-module/ngx_http_upload_module.o \
                /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c: In function Б-?ngx_http_upload_merge_loc_confБ-?:
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: Б-?ngx_garbage_collector_temp_handlerБ-? undeclared (first use in this function)
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: note: each undeclared identifier is reported only once for each function it appears in
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: passing argument 1 of Б-?ngx_conf_merge_path_valueБ-? from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected Б-?struct ngx_conf_t _Б-? but argument is of type Б-?struct ngx_path_t *Б-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: passing argument 2 of Б-?ngx_conf_merge_path_valueБ-? from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected Б-?struct ngx_path_t *_Б-? but argument is of type Б-?struct ngx_path_t _Б-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: passing argument 3 of Б-?ngx_conf_merge_path_valueБ-? from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected Б-?struct ngx_path_t *Б-? but argument is of type Б-?char *Б-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: passing argument 4 of Б-?ngx_conf_merge_path_valueБ-? makes pointer from integer without a cast [-Werror]
In file included from src/core/ngx_core.h:58:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: expected Б-?struct ngx_path_init_t *Б-? but argument is of type Б-?intБ-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1104:31: error: too many arguments to function Б-?ngx_conf_merge_path_valueБ-?
In file included from src/core/ngx_core.h:58:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_file.h:145:7: note: declared here
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c: In function Б-?ngx_http_upload_pass_form_fieldБ-?:
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1490:5: error: passing argument 1 of Б-?ngx_regex_compileБ-? from incompatible pointer type [-Werror]
In file included from src/core/ngx_core.h:63:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_regex.h:50:11: note: expected Б-?struct ngx_regex_compile_t *Б-? but argument is of type Б-?struct ngx_str_t *Б-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1490:5: error: too many arguments to function Б-?ngx_regex_compileБ-?
In file included from src/core/ngx_core.h:63:0,
                 from /home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:7:
src/core/ngx_regex.h:50:11: note: declared here
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1490:14: error: assignment makes pointer from integer without a cast [-Werror]
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1497:5: error: implicit declaration of function Б-?ngx_regex_capture_countБ-? [-Werror=implicit-function-declaration]
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1501:28: error: Б-?ngx_regex_capture_count_nБ-? undeclared (first use in this function)
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1501:54: error: expected Б-?)Б-? before string constant
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c: In function Б-?ngx_http_read_upload_client_request_bodyБ-?:
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1922:7: error: Б-?ngx_http_request_body_tБ-? has no member named Б-?to_writeБ-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c: In function Б-?ngx_http_do_read_upload_client_request_bodyБ-?:
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1991:56: error: Б-?ngx_http_request_body_tБ-? has no member named Б-?to_writeБ-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:1997:19: error: Б-?ngx_http_request_body_tБ-? has no member named Б-?to_writeБ-?
/home/mimiko/src/nginx-modules/nginx-upload-module/ngx_http_upload_module.c:2063:44: error: Б-?ngx_http_request_body_tБ-? has no member named Б-?to_writeБ-?
cc1: all warnings being treated as errors
make[1]: *_\* [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/home/mimiko/src/nginx'
make: **\* [build] Error 2

I'm on Debian Wheezy x86_64. Nginx and module latest from git.

**Comment by khavishbhundoo** [comment]
@fdintino  You can close this issue
