### ISSUE TITLE
A segfault on recent commits

### ISSUE THREAD

**Issue by benhoskings** [fdintino/nginx-upload-module#68]
Hi, I rebuilt nginx today with the latest nginx-upload-module on the `2.2` branch and my workers started segfaulting on all uploads. I found that the error seems to have been introduced in the last few commits to that branch.
- If I build against the latest commit aba1e3f34c754551f4f49e572bc86863d535609d, or ed996c4f7fedd9f2a1cce97f79192cd5c057e797, every upload segfaults.
- If I build against cd4c63128e6d63098805f9c5c27292ed430a37a6, just before `2.2-merge` was merged, everything works fine.

The config I'm using is pretty standard; here's the relevant bit: https://github.com/benhoskings/corkboard-babushka-deps/blob/master/nginx/corkboard_vhost.common.erb#L45-L62 (The erb path is rendered out to a regular path when the config is generated.)

**Comment by benhoskings** [comment]
Oops, I forgot to mention the nginx version I'm using:

```
> /opt/nginx/sbin/nginx -V
nginx version: nginx/1.6.2
built by gcc 4.9.2 20150304 (prerelease) (GCC) 
TLS SNI support enabled
configure arguments: --prefix=/opt/nginx --with-ipv6 --with-pcre --with-http_ssl_module --with-http_gzip_static_module --with-ld-opt=-lpcre --add-module=../../cd4c63128e6d63098805f9c5c27292ed430a37a6/nginx-upload-module-cd4c63128e6d63098805f9c5c27292ed430a37a6
```

**Comment by vkholodkov** [comment]
Interesting. I need more details about the segfaults, such as a backtrace. Then I will be able to look at it.

**Comment by khavishbhundoo** [comment]
@fdintino   This issue could be closed as well
