### ISSUE TITLE
nginx 1.10.0 nginx-upload-module 2.2 patch

### ISSUE THREAD

**Issue by qsq3** [fdintino/nginx-upload-module#81]
sorry this is a poorly written issue!

**Comment by jons** [comment]
this is a poorly written issue but the edits suggested in section 4 does in fact fix failure to compile upload 2.2 with nginx-1.10.1 on ubuntu 16.04 LTS for me. if i get a minute i'll make a PR for it.

**Comment by khavishbhundoo** [comment]
@fdintino  This issue can be closed now
