### ISSUE TITLE
HTTP/2 gives 500 Internal error

### ISSUE THREAD

**Issue by khavishbhundoo** [fdintino/nginx-upload-module#82]
If i enable http2 in the server block upload won't happen , instead i got a  500 Internal Server Error.I compile nginx upload module on branch 2.2
`listen 443 http2 default_server reuseport deferred;`

Error log show 
`epoll_ctl(1, 20) failed (17: File exists)`

I would be extremely grateful if someone could issue a patch for it.Sadly i don't know C :(

@Austinb  @qsq3

**Comment by crazymaggot07** [comment]
Any update for this trouble?

**Comment by Media182** [comment]
Any workaround / patch to make this great module work with HTTP2?
