### ISSUE TITLE
It can't run by https protocol. 

### ISSUE THREAD

**Issue by wisdomryw** [fdintino/nginx-upload-module#87]
I use your upload-module to achieve the uploading of big file. It runs very good in the http protocol. But when we change the Nginx server's http protocol to the http ssl protocol, it has some problems in the BS client and java client. Would you mind telling me if your upload-module supports the http ssl protocol?

**Comment by Siglud** [comment]
see #82

**Comment by Austinb** [comment]
As @Siglud pointed to check to see if you are using http2 or not.  Normal SSL (TLS) works just fine until you enable http2 at which point the module chokes.  Hopefully there is a fix for this soon but for the time being you will need to disable http2 support for uploads using this module.

**Comment by fdintino** [comment]
Fixed by #97
