### ISSUE TITLE
nginx1.11.6 add ngnix-upload-module biuld failed

### ISSUE THREAD

**Issue by hxdyj** [fdintino/nginx-upload-module#90]
nginx1.11.6 add ngnix-upload-module biuld failed.
I have patch davromaniak.txt,but also failed.
error detail is following：
/download/nginx-upload-module-master/ngx_http_upload_module.c:2805: error: ‘ngx_http_upload_sha1_ctx_t’ has no member named ‘sha1_digest’
make[1]: *** [objs/addon/nginx-upload-module-master/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/download/nginx-1.11.6'
make: *** [build] Error 2

**Comment by happystory** [comment]
I have the same problem on nginx 1.11.12, hope someone give me the solutions .Thanks!

**Comment by hxdyj** [comment]
@happystory I have already solution this problem , biuld failed because nginx version and nginx-upload-module version is not matched. I have a matched version. If you need,I share my link to you.

**Comment by happystory** [comment]
@hxdyj Could you please share your link with me or tell me the suitable version of nginx matched this module. Thank you very much!

**Comment by hxdyj** [comment]
http://pan.baidu.com/s/1o8iBZEa    this is nginx1.6.3 download address
http://pan.baidu.com/s/1i4YCOdv   this is nginx-upload-module download address

I find although it can biuld ,but it's not useful in general.finally I give up this way.

**Comment by hxdyj** [comment]
@happystory 
http://pan.baidu.com/s/1o8iBZEa this is nginx1.6.3 download address
http://pan.baidu.com/s/1i4YCOdv this is nginx-upload-module download address
I find although it can biuld ,but it's not useful in general.finally I give up this way.

**Comment by happystory** [comment]
I build it success. But when I upload a file to server, it gives me a 503 error. The detail information is "503 Service Temporarily Unavailable".

**Comment by Austinb** [comment]
This has nothing to do with version matching.  It has to do with nginx continuing to move forward breaking some dependencies for this module preventing it from compiling.  This issue should be fixed in the 2.255 branch.   Please try that and upgrade your version since 1.13 is the current stable branch.

**Comment by khavishbhundoo** [comment]
@fdintino  You can close this issue
