### ISSUE TITLE
500 Internal Server Error http/2

### ISSUE THREAD

**Issue by crazymaggot07** [fdintino/nginx-upload-module#92]
Hello all,
I have nginx 1.12.1 with http/2 over https. I have downloaded and installed this module https://github.com/Austinb/nginx-upload-module.

When I try upload photo, I get this error:
[alert] 17939#0: *17 epoll_ctl(1, 117) failed (17: File exists).

My modules:
--with-file-aio --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-http_v2_module --with-openssl=/opt/openssl-1.1.0c/ --add-module=/opt/nginx-upload-module-2.2 --add-module=/opt/nginx-upload-progress-module-master/

Please help my with this problem. Thanks.

Best regards

**Comment by myxuchangbin** [comment]
#82

**Comment by fdintino** [comment]
Fixed by #97
