### ISSUE TITLE
Request: Project manager

### ISSUE THREAD

**Issue by Austinb** [fdintino/nginx-upload-module#94]
I would like to request someone to take over managing this project if possible so that issues and other problems that show up can be resolved with the proper answers.  Many of the responses on tickets still use old and no longer supported versions of nginx when suitable fixes exist for later versions 1.11+.  Also most of the pull requests should be closed out due to their age. 

Also if it is possible someone should clean up the branches.  I am sure many people are confused as to which version to use and is "stable".  Master and most of the other branches except 2.255 are very old.  Many people still use this project as you can see by the stats.   

@vkholodkov would something like this be possible?

**Comment by dup2** [comment]
I fully support this. The current state makes it very difficult to use this module for newer nginx versions and the same compile issues keep coming up time and again.

We are otherwise very happy with this module!

**Comment by vkholodkov** [comment]
That's possible, we need a volunteer then!

The following skills are required:
* good command of English, primarily written
* proficiency in C
* familiarity with Nginx

Any applicants?

**Comment by yapus** [comment]
I've been using this module before and even made some adjustments for our needs (like checking md5 for individual uploaded chunks). So if no other volunteer will pop up – i can try taking care of that...

**Comment by Austinb** [comment]
I can offer assistance with managing the project itself but I am not a proficient in C as others who have committed.  If you need extra help with managing the project such as issues I would be happy to lend some time but when it comes to bug fixes or pull requests dealing with the code itself (outside of simple compiling debugging) I would not be your person.

**Comment by fdintino** [comment]
@vkholodkov I volunteer.

**Comment by vkholodkov** [comment]
Hi Frankie! Thank you for doing that! Do you have time on Friday between 7pm - 9pm CET for a skype call to do handover? It works for me on the weekend as well, otherwise next week.

**Comment by fdintino** [comment]
Sure! My contact email is on my profile page.

**Comment by fdintino** [comment]
Repo ownership has been transferred.

**Comment by cbj4074** [comment]
@fdintino I can't tell you how glad I am to see you assume responsibility for this project! THANK YOU!
